

class CONST:
    CAR = 'passenger'
    BUS = 'bus'
    EMERGENCY = 'emergency'
    BUS_PASSENGER = 'bus_passenger'
    PEDESTRIAN = 'pedestrian'

    AVAILABLE_VEHICLE_ACTORS = [CAR, BUS, EMERGENCY]
    AVAILABLE_PERSON_ACTORS = [BUS_PASSENGER]

    ACCIDENT_GENERATION_SYSTEM = "ACCIDENT_GENERATION_SYSTEM"
    SLOW_DOWN_GENERATION_SYSTEM = "SLOW_DOWN_GENERATION_SYSTEM"

    REGULAR_TRAFFIC = 'regular_traffic'
    ANOMALOUS_TRAFFIC = 'anomalous_traffic'
    ACCIDENT_BASED_ANOMALOUS_TRAFFIC = 'accident_based_anomalous_traffic'
