

class CONST:
    CAR = 'passenger'
    BUS = 'bus'
    EMERGENCY = 'emergency'
    BUS_PASSENGER = 'bus_passenger'
    PEDESTRIAN = 'pedestrian'

    AVAILABLE_VEHICLE_ACTORS = [CAR, BUS, EMERGENCY]
    AVAILABLE_PERSON_ACTORS = [BUS_PASSENGER]

    TRAFFIC_LIGHT_SYSTEM = 'TRAFFIC_LIGHT_SYSTEM'
    EXCLUSIVE_LANE_SYSTEM = 'EXCLUSIVE_LANE_SYSTEM'

    AVAILABLE_CONTROL_SYSTEMS = [TRAFFIC_LIGHT_SYSTEM, EXCLUSIVE_LANE_SYSTEM]
